services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DB_HOST=db
      - DB_NAME=gestion_invitation
      - DB_SA_PASSWORD=yassine@2021
      - DB_PORT=1433
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "yassine@2021"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
volumes:
  db_data:
